package live.chenchen.cxf2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2017-05-03T11:02:53.064+08:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://cxf2.chenchen.live/", name = "MyServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MyServicePortType {

    @WebMethod
    @WebResult(name = "getPersonByIdResponse", targetNamespace = "http://cxf2.chenchen.live/", partName = "parameters")
    public ArrayOfPersonType getPersonById(
        @WebParam(partName = "parameters", name = "getPersonByIdRequest", targetNamespace = "http://cxf2.chenchen.live/")
        AttachmentType parameters
    );
}
