
package live.chenchen.cxf2;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2017-05-02T18:45:45.451+08:00
 * Generated source version: 2.3.3
 * 
 */
 
public class MyServicePortType_MyServiceSoap_Server{

    protected MyServicePortType_MyServiceSoap_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new MyServicePortTypeImpl();
        String address = "http://localhost:5555/myservice";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new MyServicePortType_MyServiceSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
