
/*
 * 
 */

package live.chenchen.cxf2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2017-05-03T11:02:53.076+08:00
 * Generated source version: 2.3.3
 * 
 */


@WebServiceClient(name = "MyService", 
                  wsdlLocation = "file:/D:/tmp/workspace/acars/cxf/pesonservice.wsdl",
                  targetNamespace = "http://cxf2.chenchen.live/") 
public class MyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf2.chenchen.live/", "MyService");
    public final static QName MyServiceSoap = new QName("http://cxf2.chenchen.live/", "MyServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/tmp/workspace/acars/cxf/pesonservice.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/D:/tmp/workspace/acars/cxf/pesonservice.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns MyServicePortType
     */
    @WebEndpoint(name = "MyServiceSoap")
    public MyServicePortType getMyServiceSoap() {
        return super.getPort(MyServiceSoap, MyServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyServicePortType
     */
    @WebEndpoint(name = "MyServiceSoap")
    public MyServicePortType getMyServiceSoap(WebServiceFeature... features) {
        return super.getPort(MyServiceSoap, MyServicePortType.class, features);
    }

}
