package live.chenchen.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3 2011-04-14T16:44:40.671+08:00
 * Generated source version: 2.3.3
 * 
 */

@WebService(targetNamespace = "http://cxf.shengsiyuan.com/", name = "MyService")
@XmlSeeAlso( { ObjectFactory.class })
public interface MyService
{

	@WebResult(name = "helloResult", targetNamespace = "")
	@RequestWrapper(localName = "hello", targetNamespace = "http://cxf.shengsiyuan.com/", className = "com.shengsiyuan.cxf.Hello")
	@WebMethod
	@ResponseWrapper(localName = "helloResponse", targetNamespace = "http://cxf.shengsiyuan.com/", className = "com.shengsiyuan.cxf.HelloResponse")
	public java.lang.String hello(
			@WebParam(name = "username", targetNamespace = "") java.lang.String username,
			@WebParam(name = "password", targetNamespace = "") java.lang.String password);

	@WebResult(name = "return", targetNamespace = "")
	@RequestWrapper(localName = "add", targetNamespace = "http://cxf.shengsiyuan.com/", className = "com.shengsiyuan.cxf.Add")
	@WebMethod
	@ResponseWrapper(localName = "addResponse", targetNamespace = "http://cxf.shengsiyuan.com/", className = "com.shengsiyuan.cxf.AddResponse")
	public int add(@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);
}
