package live.chenchen.cxf4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2017-05-02T13:33:42.756+08:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://cxf2.chenchen.live/", name = "MyService")
@XmlSeeAlso({ObjectFactory.class})
public interface MyService {

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://cxf2.chenchen.live/", className = "live.chenchen.cxf2.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://cxf2.chenchen.live/", className = "live.chenchen.cxf2.HelloResponse")
    @WebResult(name = "helloResult", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );
}
