
package live.chenchen.cxf4;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2017-05-02T13:33:42.777+08:00
 * Generated source version: 2.3.3
 * 
 */
 
public class MyService_MyServiceImplPort_Server{

    protected MyService_MyServiceImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new MyServiceImpl();
        String address = "http://localhost:5555/myservice";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new MyService_MyServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
